### ISSUE TITLE
Unreadable Text on Dark Styles.

### ISSUE THREAD

**Issue by stevegill** [RRUZ/vcl-styles-plugins#33] opened 2016-10-17 03:00 UTC
When I use the darker styles with InnoSetup the text is virtually unreadable. The font colour appears to be black when it should be white. 

Inno Script Studio 5.5.9 (u) 
VCL Styles Inno 1.5.4.1 

Here are two examples of the problem: 

http://www.stevegill.com.au/images/WelcomeScreenFontColour.png 
http://www.stevegill.com.au/images/InstallScreenFontColour.png 

Thanks, 

Steve

**Comment by RRUZ** [comment] 2016-10-17 04:24
Please attach a sample script to reproduce the issue.

**Comment by stevegill** [comment] 2016-10-17 06:38
Sample script attached as requested.

**Comment by stevegill** [comment] 2016-10-19 06:31
[Example1.zip](https://github.com/RRUZ/vcl-styles-plugins/files/538099/Example1.zip)

**Comment by stevegill** [comment] 2016-10-20 08:40
Any luck with finding out what the issue is?

= Steve

**Comment by RRUZ** [comment] 2016-10-20 19:09
Unfortunately I'm not able to reproduce the issue, I just tried your sample script and works as expected. 

![bluegraphite](https://cloud.githubusercontent.com/assets/11446959/19574001/cf56d290-96de-11e6-95c9-d5e327ebcfa0.png)

In what Windows versions are you testing this?
Are you tested the installer in another machines?

Also Try using this Vcl Style file

[BlueGraphite.zip](https://github.com/RRUZ/vcl-styles-plugins/files/542668/BlueGraphite.zip)

**Comment by stevegill** [comment] 2016-10-21 04:49
That's really strange.  I have tested it on two computers: one running Windows 7 Professional and the other Windows 10 Home.

I tried the file you attached but I'm getting the same result.

**Comment by RRUZ** [comment] 2016-10-21 15:08
Are you tried with another Styles?

**Comment by stevegill** [comment] 2016-10-21 21:39
Yes it's the same with all of the dark styles.  The odd thing is, if I add a message box it displays fine.

[http://www.stevegill.com.au/images/MsgBoxExample.png](url)

**Comment by stevegill** [comment] 2016-10-24 23:20
Could it be something on my computer causing this when the installer is being compiled?

**Comment by RRUZ** [comment] 2016-10-24 23:29
"....Could it be something on my computer causing this when the installer is being compiled?"
 I doubt that, because the colors used to drawn the text are resolved in runtime depending of the active VCL Style (Skin).

**Comment by stevegill** [comment] 2016-11-02 04:36
I scanned my computer for older versions of the DLL but there weren't any.  I'm not sure what else I can check.

**Comment by stevegill** [comment] 2016-12-03 06:41
Here's an update for you.  I just upgraded to a new computer and running Windows 10 Professional and now the dark styles are working fine!!

**Closed** 2017-02-27 02:23 UTC
